server:
  port: 8080
  
logging:
  level:
    root: debug
    
spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    usrername: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
    
      